# This is the configuration used to check the rubocop source code.
AllCops:
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

AllCops:
  Exclude:
    - spec/support/spec_helper.rb
    - spec/rails_helper.rb
    - app/authentication/*
    - app/controllers/application_controller.rb

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Max: 99
  Exclude:
    - "**/*_spec.rb"

Documentation:
  Enabled: false

LineLength:
  Max: 99

HasAndBelongsToMany:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false