version: 2
jobs:
 build:
   docker:
     - image: ruby:2.3.4
       environment:
         PGHOST: 127.0.0.1
         PGUSER: wilbert
         RAILS_ENV: test
     - image: redis:3.2
     - image: postgres:9.4.1
       environment:
         POSTGRES_USER: wilbert

   working_directory: /home/Documents/repo/trainning-wilbert
   steps:
     - checkout
     - run: apt-get update -qq && apt-get install -y build-essential nodejs
     - run: bundle install
     - run: bundle exec rake db:create db:schema:load --trace
     - run: bundle exec rake db:migrate
     - run: bundle exec rubocop app spec -R --format simple
     - run: bundle exec rspec