jobs_send_email:
  name: 'jobs_send_email' #must be uniq!
  cron: '*/1 * * * *' # execute at 1 minute of every hour, ex: 12:01, 13:01, 14:01, 15:01...etc(HH:MM)
  class: 'NotifyRentDaysWorker'
  queue: notify_rent_total_days_worker

  # #OPTIONAL
  # 'queue' => 'name of queue',
  # 'args'  => '[Array or Hash] of arguments which will be passed to perform method',
  # 'active_job' => true,  # enqueue job through rails 4.2+ active job interface
  # 'queue_name_prefix' => 'prefix', # rails 4.2+ active job queue with prefix
  # 'queue_name_delimiter' => '.'  # rails 4.2+ active job queue with custom delimiter
  # */1 * * * * cada minutos  
