# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
 secret_key_base: 3755fcb5b29a7fb580ae97f2e39d2c609e93bdde01ab4108ea4c3aa3ad040b2232c250dd1dcde5219159eb5ea9b1c0545c7930e50bee368adb5404bdefbee6f3
 book_api: http://polls.apiblueprint.org/api/v1/books
 test_api: https://jsonplaceholder.typicode.com/posts
 google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %> 
 google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %> 
 mailgun_apy_key: <%= ENV["MAILGUN_APY_KEY"] %>
 mailgun_password: <%= ENV["MAILGUN_PASSWORD"] %>
 mailgun_apy_url: <%= ENV["MAILGUN_APY_URL"] %>
 mailgun_smtp_login: <%= ENV["MAILGUN_SMTP_LOGIN"] %>
 mailgun_smtp_hotname: <%= ENV["MAILGUN_SMTP_HOSTNAME"] %> 
 mailgun_domain: <%= ENV["MAILGUN_DOMAIN"] %> 
test:
 secret_key_base: 0668db246f2e19c18a2d0bdc545318a981a3f8ff8ceaa68562c8f7ecb220512a421ea86f3be07b90bba1be9be29e1f4cf466f0e5ff6e94121a4c37bf937e843f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
 secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
 book_api: http://polls.apiblueprint.org/api/v1/books
 test_api: https://jsonplaceholder.typicode.com/posts
 google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %> 
 google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
 mailgun_apy_key: <%= ENV["MAILGUN_APY_KEY"] %>
 mailgun_password: <%= ENV["MAILGUN_PASSWORD"] %>
 mailgun_apy_url: <%= ENV["MAILGUN_APY_URL"] %>
 mailgun_smtp_login: <%= ENV["MAILGUN_SMTP_LOGIN"] %>
 mailgun_smtp_hotname: <%= ENV["MAILGUN_SMTP_HOSTNAME"] %> 
 mailgun_domain: <%= ENV["MAILGUN_DOMAIN"] %>
